import { Router, Request, Response } from "express";
import pool from "../db";
import { ResultSetHeader } from "mysql2/promise";

const router = Router();

router.post("/create", async (req: Request, res:Response) => {
    try {
        const {
            first_name, last_name, appearance,
            strength, dexterity, constitution, intelligence, salary,
            weapon_id, armour_id, user_id, team_id
        } = req.body;

        //This query is made so that it won't be a SQL risk.
        const [result] = await pool.query<ResultSetHeader>(
            `INSERT INTO Fighter
                (first_name, last_name, appearance, strength, dexterity,
                constitution, intelligence, salary, Weapons_weapon_id, Armour_armour_id, User_user_id, Team_team_id)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,[
                first_name, last_name, appearance, strength,
                dexterity, constitution, intelligence, salary,
                weapon_id, armour_id, user_id, team_id]
        );

        //The ID is the auto-generated by the db so send it back to the client.
        res.status(201).json({ fighter_id: result.insertId});
    } catch (err) {
        console.error("API FAILED to add fighter: ", err);
        res.status(500).json({ error: "Failed to createfighter." });
    }
});

export default router;